### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by kgraefe** [bbqsrc/eventlog#4]
One thing that always bugged me was that docs.rs is not able to build the documentation: https://docs.rs/crate/eventlog/0.1.1

Something like https://github.com/retep998/winapi-rs/blob/0.3/Cargo.toml#L17 might fix it (maybe with architecture `x86_64-pc-windows-gnu`)? However I don't have a good way to test this.

**Comment by bbqsrc** [comment]
Poked at it, still nothing.

https://docs.rs/crate/eventlog/0.2.2/builds/747288

It is cross-compiling on linux but failing to find the mc binaries.

**Comment by kgraefe** [comment]
Fixed it :-)
