### ISSUE TITLE
Incorrect ReportEventW arguments

### ISSUE THREAD

**Issue by villanyibalint** [bbqsrc/eventlog#8]
Hi there!

I am using version 0.3.0 on Windows 11 22631.4460. I am getting `0x800706F7 The stub received bad data` on every log attempt, although this is silently consumed by the library, I verified it with debugging.

I see that you upgraded to using windows-rs recently. Unfortunately, I believe there is a mistake in using `ReportEventW` at:
https://github.com/bbqsrc/eventlog/blob/f56243ad5ba8d8312a6d3a49ad97f08c5fabc6d5/src/lib.rs#L119C12-L128C15

The sixth parameter of `ReportEventW` in windows-rs seems to be [`dwdatasize` of the Win32 ReportEventW](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-reporteventw), which is the size of the binary data attached to the event, not the number of strings in the event message buffer. [windows-rs calculates the latter from the length of the vector itself.](https://github.com/microsoft/windows-rs/blob/a8e14c75581bb89fc244ad480f98567be972aea2/crates/libs/windows/src/Windows/Win32/System/EventLog/mod.rs#L480C1-L487C2). This means any event with a message attached should fail, as `lprawdata` is always None.

Please correct me if I made a mistake, otherwise I can create a PR if you'd like.

**Comment by bbqsrc** [comment]
PR pls!

**Comment by villanyibalint** [comment]
Added a PR #9

**Comment by villanyibalint** [comment]
Thanks! The E2E test wasn't passing for me btw, have you thought about turning on testing in the workflow? It should just work; the windows runner has the privileges to modify the registry so it can register new sources. [See my fork's workflow results.](https://github.com/villanyibalint/eventlog/actions/runs/11821257225/job/32935559125) (Maybe also turn on workflows for PRs?) 

Also any chance you will push the fix to a new version on crates? The reason I arrived at eventlog is because of a downstream project where I could use it.

**Comment by bbqsrc** [comment]
I commented in the pr to let me know if it passes locally haha. I’m happy to have you as a maintainer since i don’t have a lot of time to manage these crates anymore and happy to provide advice and a second set of eyes though.
